spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springboottemplate
    username: springuser
    password: springuser
    driverClassName: org.postgresql.Driver

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true